export const RETARDANT_LOWER_LIMIT = 10;
export const RETARDANT_UPPER_LIMIT = 20;
export const NUMBER_OF_RETARDANT_EQUIVALENT_TO_ONE_ABSENCE = 3;
export const  ANTIQUITY_EXEMPT_FOR_APPLY_RETARDANT = 10;